name: pytest

on:
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: pytest (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - id: set-pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - id: cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.set-pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - run: pytest -nauto -v tests
